# Testing a deploying on a single node
version: "3.9"

services:
  network-helper:
    build: network-helper/
    command: bash
  server:
    container_name: ping-pong-server
    hostname: ping-pong-server
    build: pong-server/
  client:
    # container_name: ping-pong-client
    hostname: ping-pong-client
    deploy:
      replicas: 3
    build: ping-client/
    depends_on:
      - server
  prometheus:
    container_name: prometheus
    image:  "bitnami/prometheus:latest"
    volumes:
      - ./prometheus/config.yaml:/opt/bitnami/prometheus/conf/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
    -  3000:3000
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
  # sqlServer:
  #   container_name: sqlserver2019
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=Dan123456
  #   ports:
  #     - 1401:1433

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1