# Testing a deploying on a single node with metrics
version: "3.9"

services:
  network-helper:
    container_name: network-helper
    hostname: network-helper
    build:
      context: .
      dockerfile: network-helper/Dockerfile
  server:
    container_name: ping-pong-server
    hostname: ping-pong-server
    build: pong-server/
  client:
    # container_name: ping-pong-client
    hostname: ping-pong-client
    deploy:
      replicas: 3
    build: ping-client/
    depends_on:
      - server
  prometheus:
    container_name: prometheus
    image:  "bitnami/prometheus:latest"
    hostname: prometheus
    volumes:
      - ./prometheus/config.yaml:/opt/bitnami/prometheus/conf/prometheus.yml
    ports:
      - 9090:9090
  # sqlServer:
  #   container_name: sqlserver2019
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=Dan123456
  #   ports:
  #     - 1401:1433

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1